name: CI

# This workflow will run on any pull request or push to main, master branches
# It checks code quality (lint) and verifies the app builds correctly with different Node.js versions
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint -- --no-fix
        
  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Check package-lock.json
      run: |
        if git diff --name-only | grep -q "package-lock.json"; then
          echo "⚠️ Warning: package-lock.json was modified during the build. This might indicate inconsistent dependencies."
          git diff package-lock.json
        fi
      
  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: always()
    steps:
    - name: Report status
      run: |
        if [ "${{ needs.lint.result }}" == "success" ] && [ "${{ needs.build.result }}" == "success" ]; then
          echo "✅ CI passed! The codebase builds successfully and has no lint errors."
        else
          echo "❌ CI failed! Please check the logs above for details."
          exit 1
        fi 